// apps/vue3/src/components/AppTabBar.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const route = useRoute();
const router = useRouter();

const TABS = [
  { name: 'home', path: '/home', label: '首页', icon: 'wap-home-o' },
  { name: 'todos', path: '/todos', label: '待办', icon: 'todo-list-o' },
  { name: 'profile', path: '/profile', label: '我的', icon: 'user-o' },
] as const;

const active = computed({
  get: () => (route.name as string) || 'home',
  set: (name: string) => {
    const tab = TABS.find((item) => item.name === name);
    if (tab && route.path !== tab.path) router.push(tab.path);
  },
});
</script>

<template>
  <van-tabbar v-model="active" route fixed placeholder safe-area-inset-bottom>
    <van-tabbar-item
      v-for="tab in TABS"
      :key="tab.name"
      :name="tab.name"
      :icon="tab.icon"
      :to="tab.path"
    >
      {{ tab.label }}
    </van-tabbar-item>
  </van-tabbar>
</template>

// apps/react/src/components/AppTabBar.tsx
import { TabBar } from 'antd-mobile';
import { AppOutline, UnorderedListOutline, UserOutline } from 'antd-mobile-icons';
import { useLocation, useNavigate } from 'react-router-dom';

const TABS = [
  { key: '/home', title: '首页', icon: <AppOutline /> },
  { key: '/todos', title: '待办', icon: <UnorderedListOutline /> },
  { key: '/profile', title: '我的', icon: <UserOutline /> },
];

function AppTabBar() {
  const navigate = useNavigate();
  const location = useLocation();

  // 取当前路径首段匹配 tab，避免带 query 时无法高亮
  const active = TABS.find((t) => location.pathname.startsWith(t.key))?.key ?? '/home';

  return (
    <TabBar
      activeKey={active}
      onChange={(key) => void navigate(key)}
      className="app-tabbar"
      safeArea
    >
      {TABS.map((tab) => (
        <TabBar.Item key={tab.key} icon={tab.icon} title={tab.title} />
      ))}
    </TabBar>
  );
}

export default AppTabBar;
